version: '3.8'
services:
  redis-node1:
    image: redis:latest
    container_name: redis-node1
    ports:
      - "6379:6379"
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]

  redis-node2:
    image: redis:latest
    container_name: redis-node2
    ports:
      - "6380:6379"
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]

  redis-node3:
    image: redis:latest
    container_name: redis-node3
    ports:
      - "6381:6379"
    command: ["redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]

networks:
  default:
    driver: bridge

